### ISSUE TITLE
Need support encoding utf-8

### ISSUE THREAD

**Issue by archonwang** [Hartorn/tfs2svn#3]
Hi， I found that the commit log is not support utf-8.  how to fix it ? Thanks

when I change tfs commit log in Chiniese, I found when I import svn the commit log has been changed into ???????.

**Comment by Hartorn** [comment]
Hi,

@archonwang
I will have a look at that today, see if there is need for an option, or if it is a problem with the code.
Is the repossitory you wanted to convert public ? If so, can you give me the url ?

**Comment by archonwang** [comment]
Hi， @Hartorn 
Thanks for your reply. I have no repository about the tfs2svn. and I met the issue for I used the tool to convert my repository into svn.

but if you have time, please check and add html file used utf-8 encoding .Thanks so much.

**Comment by Hartorn** [comment]
@archonwang 
Found the issue : problem is that commit message is converted as it was ASCII.
Will try to add configuration for that.

**Comment by archonwang** [comment]
Hi,  @Hartorn ， 
if you have fixed it ,please build beta application and I will test it ASAP.
Thanks.

**Comment by Hartorn** [comment]
Hi
@archonwang : Here is the build
Uninstall any previously installed version before installing this one.
https://github.com/Hartorn/tfs2svn/releases/tag/V3.0-alpha

Would be glad to have some return on that version

**Comment by archonwang** [comment]
Hi, @Hartorn 
Thanks. I will test it ASAP.

**Comment by archonwang** [comment]
Hi, @Hartorn ，
 The utf-8 encoding option worked well, and I have checked it in some repositories.

Thanks so much. and I will test other new feature for some time.

**Comment by Hartorn** [comment]
Hi @archonwang 

Good to know it works well.
If you have any problems, or need any new features, feel free to ask.
